### ISSUE TITLE
The system did not recognize any cars.

### ISSUE THREAD

**Issue by firecoolman** [danielbob32/ParkingSpace#1]
I'm sorry, I followed your steps to install all the packages, but when I run the code, the screen only shows 26 empty slots. It did not capture any cars.

I checked your related website, but I might not be very familiar with the code, so I still don't know how to solve this problem. I would like to ask if you have encountered any similar issues or have any experience with this.

Thank you very much for your dedication. Your detailed description of the program shows your passion and helps others feel it too.

**Comment by danielbob32** [comment]
Hi there!

To help you better, please attach a screenshot for me to review, and also provide the script you are currently running.

Based on your description, it seems like the algorithm is working as expected since you are able to see empty slots. However, there might be issues with the model’s ability to recognize the cars.

To assist you further, please provide me with the following details:

1. A screenshot of the current output.
2. The script you are using.
3. Any error messages or logs you are encountering.

Looking forward to your response!

**Comment by firecoolman** [comment]
Hi danielbob32!
<img width="964" alt="parking" src="https://github.com/user-attachments/assets/0d74116c-c1f7-4616-a859-91c5d5e44752">

I am running ParkingSpace.py file

<img width="824" alt="parking_2" src="https://github.com/user-attachments/assets/769b016d-2091-4290-b9ad-4ed0ed182571">

Here is the log of my execution. It seems there are no error messages. I have also attached the package versions I used.

Thank you very much for your help.

**Comment by danielbob32** [comment]
Hi there,

Thank you for your patience. I will try to respond as soon as possible.

I am experiencing the same results as you. The model seems to be working as expected, but I've noticed a potential issue with the version being used. I was previously using ultralytics==8.1.34, while the current version is 8.2.66. This difference might be causing issues with the processing of each frame.

It appears there might be a problem with the binary and the probability map fusion, which could explain why no cars are being detected even though the model indicates otherwise.

If you look at the main repo page, you'll notice that the detected cars are shown in an orange mask. However, with the new model version, the mask appears as translucent white.

I will work on fixing this issue and keep you updated.

Thank you very much for your patience!

**Comment by firecoolman** [comment]
You're welcome! I'm glad to hear everything is working fine now. If you have any more questions or need further assistance, feel free to ask.

Best regards.
